version = 0.1
[default.deploy.parameters]
stack_name = "rezzy-rate"
resolve_s3 = true
s3_prefix = "rezzy-rate"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FrontendUrl=\"https://rezzyrate.com\" StripeSecretParam=\"/stripe/test_secret\" StripeWebhookSecretParam=\"/stripe/webhook_secret_test\""
image_repositories = []
