name: Sync Folder to S3

on:
  push:
    branches:
      - main
    paths:
      - "www/**"

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   
      contents: read     

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::728866571318:role/rezzyRate_github_sync_role
          aws-region: us-east-1

      - name: Sync folder to S3
        run: aws s3 sync ./www s3://rezzyrate-customresourcestack-cclxs28-s3bucketroot-84sryafe4cup --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1F5MG7G6HTTLR \
            --paths "/*"
